# Generated by Django 5.0.2 on 2024-02-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
    ]
