# Generated by Django 5.0.2 on 2024-02-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockWeight',
            fields=[
                ('livestock_weight_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('measurement_date', models.DateField()),
                ('livestock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock')),
            ],
        ),
    ]
