# Generated by Django 5.0.2 on 2024-02-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.plot')),
            ],
        ),
    ]
