# Generated by Django 5.0.2 on 2024-02-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockDosage',
            fields=[
                ('dosage_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=100)),
                ('dosage_amount', models.FloatField()),
                ('dosage_unit', models.CharField(max_length=50)),
                ('administration_date', models.DateField()),
                ('livestock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock')),
            ],
        ),
    ]
