# Generated by Django 5.0.2 on 2024-02-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('livestock_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.plot')),
            ],
        ),
    ]
